### ISSUE TITLE
Specifying MYSQL_ROOT_PASSWORD doesn't work

### ISSUE THREAD

**Issue by bperel** [jamiejackson/docker-mariadb-replication#1]
Using this docker-compose.yml:

```yaml
version: '3'
services:

  db_master:
    image: jamiejackson/mariadb-replication:10.2
    container_name: db_master
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - MYSQL_ROOT_PASSWORD=changeme

  db_slave1:
    image: jamiejackson/mariadb-replication:10.2
    container_name: db_slave1
    depends_on:
      - "db_master"
    ports:
     - "3308:3306"
    links:
      - db_master:master
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - MASTER_HOST=master
      - MASTER_PORT=3306
      - MYSQL_ROOT_PASSWORD=changeme

  db_slave2:
    image: jamiejackson/mariadb-replication:10.2
    container_name: db_slave2
    depends_on:
      - "db_master"
    ports:
     - "3309:3306"
    links:
      - db_master:master
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - MASTER_HOST=master
      - MASTER_PORT=3306
      - MYSQL_ROOT_PASSWORD=changeme
```

leads to errors when starting containers:

```
...
db_slave2    | Version: '10.2.6-MariaDB-10.2.6+maria~jessie-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
db_slave1    | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
db_master    | 2017-07-07 13:42:17 139814339180288 [Warning] 'proxies_priv' entry '@% root@6bdae1f3f1e3' ignored in --skip-name-resolve mode.
db_master    |
db_master    | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-master.sh
db_master    | Creating replication user ...
db_master    | 2017-07-07 13:42:17 139814339180288 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
db_master    | ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
db_slave2    | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
db_slave1    | 2017-07-07 13:42:19 140034053596928 [Warning] 'proxies_priv' entry '@% root@3af6dcf16ce0' ignored in --skip-name-resolve mode.
db_slave1    |
db_slave1    | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-slave.sh
db_slave1    | Making sure master is responding
db_slave1    | Master not responding; sleeping for a second.
db_slave2    | 2017-07-07 13:42:20 139964093945600 [Warning] 'proxies_priv' entry '@% root@dd74261c15cb' ignored in --skip-name-resolve mode.
db_slave2    |
db_slave2    | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-slave.sh
db_slave2    | Making sure master is responding
db_slave2    | Master not responding; sleeping for a second.
db_slave1    | Master not responding; sleeping for a second.
db_slave2    | Master not responding; sleeping for a second.
db_slave1    | Master not responding; sleeping for a second.
db_slave2    | Master not responding; sleeping for a second.
db_slave1    | Master not responding; sleeping for a second.
db_slave2    | Master not responding; sleeping for a second.
...
```

Also tried to comment the MYSQL_ALLOW_EMPTY_PASSWORD line, didn't work either

**Comment by olublessed** [comment]
same here

**Comment by jamiejackson** [comment]
Give it a shot with the latest. Example:

https://github.com/jamiejackson/docker-mariadb-replication/blob/master/bin/start.sh

And:

```yml
version: '3'
services:

  db_master:
    image: jamiejackson/mariadb-replication:10.2
    container_name: db_master
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      #- MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  db_slave1:
    image: jamiejackson/mariadb-replication:10.2
    container_name: db_slave1
    depends_on:
      - "db_master"
    ports: 
     - "3308:3306"
    links:
      - db_master:master
    restart: unless-stopped
    environment:
      #- MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MASTER_HOST=master
      - MASTER_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  db_slave2:
    image: jamiejackson/mariadb-replication:10.2
    container_name: db_slave2
    depends_on:
      - "db_master"
    ports: 
     - "3309:3306"
    links:
      - db_master:master
    restart: unless-stopped
    environment:
      #- MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MASTER_HOST=master
      - MASTER_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
```
